<a href="https://colab.research.google.com/github/Miladatasys/sic_ai/blob/main/intro_pandas_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Clase 3 Introducción a Pandas y Numpy

# NumPy
## NumPy (Numerical Python) es una biblioteca que proporciona soporte para crear y manipular matrices grandes y multidimensionales, junto con una colección de funciones matemáticas para operar con estas matrices de manera eficiente.

Características principales de NumPy:


*   Arrays multidimensionales: NumPy proporciona una estructura de datos llamada ndarray, que permite manejar matrices de cualquier dimensión.
*   Funciones matemáticas: Incluye funciones para operaciones algebraicas, estadísticas y lógicas.
*   Interoperabilidad: Funciona bien con otras bibliotecas como SciPy y Matplotlib.








In [2]:
import numpy as np

array_1d = np.array([1, 2, 3, 4, 5])
print("Array unidimensional:\n", array_1d)

array_2d =np.array([[1,2,3], [4,5,6]])
print("Array bidimensional", array_2d)

array_3d = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
print("Array tridimensional:\n", array_3d)

#Operaciones básicas
print("Suma de todos los elementos del array_2: ", np.sum(array_2d))
print("Promedio de todos sus elementos: ", np.mean(array_2d))
print("Máximo valor del array_2: ", np.max(array_2d))
print("Mínimo valor del array_2: ", np.min(array_2d))

Array unidimensional:
 [1 2 3 4 5]
Array bidimensional [[1 2 3]
 [4 5 6]]
Array tridimensional:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Suma de todos los elementos del array_2:  21
Promedio de todos sus elementos:  3.5
Máximo valor del array_2:  6
Mínimo valor del array_2:  1


# Pandas
Pandas es una biblioteca que proporciona estructuras de datos y herramientas de análisis de datos flexibles y eficientes. Es especialmente útil para datos tabulares, como los que se encuentran en hojas de cálculo o bases de datos.

Características principales de Pandas:


*   Series: Estructura unidimensional similar a una lista o un array de NumPy.
*   DataFrame: Estructura bidimensional similar a una tabla en una base de datos o una hoja de cálculo de Excel.
*   Funciones de E/S: Herramientas para leer y escribir datos en diversos formatos (CSV, Excel, SQL, etc.).
*   Manipulación de datos: Funciones para filtrar, agrupar, pivotar, fusionar, etc.









In [6]:
import pandas as pd

serie = pd.Series([10, 20])
print("Serie:\n", serie)

data = pd.DataFrame({'Nombre': ['Mila', 'Data'],
                   'Edad': [30, 50],
                   'Ciudad': ['Ciudad A', 'Ciudad B']})
df = pd.DataFrame(data)
print("Dataframe:\n", df)

print("Columna 'Edad':\n", df['Edad'])

print("Filtrar por Edad > 30:\n", df[df['Edad'] > 30])

print("Filtrar por Ciudad == 'Ciudad A':\n", df[df['Ciudad'] == 'Ciudad A'])

Serie:
 0    10
1    20
dtype: int64
Dataframe:
   Nombre  Edad    Ciudad
0   Mila    30  Ciudad A
1   Data    50  Ciudad B
Columna 'Edad':
 0    30
1    50
Name: Edad, dtype: int64
Filtrar por Edad > 30:
   Nombre  Edad    Ciudad
1   Data    50  Ciudad B
Filtrar por Ciudad == 'Ciudad A':
   Nombre  Edad    Ciudad
0   Mila    30  Ciudad A
